# Generated by Django 4.1.7 on 2023-02-19 20:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherfio', models.CharField(max_length=100, verbose_name="O'qituvchi ism, familyasi")),
                ('kasbi', models.CharField(help_text="masalan: direktor yoki O'qituchi (matematika)", max_length=100, verbose_name='Qaysi fan yoki qanday ish bajarishi')),
                ('teacher_info', ckeditor.fields.RichTextField(verbose_name="Qo'shimcha ma'lumotlar")),
            ],
            options={
                'verbose_name': "Yangi ustoz qo'shish",
                'verbose_name_plural': 'Ustozlar',
            },
        ),
    ]
