# Generated by Django 4.1.7 on 2023-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustozlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='teacher_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
