# Generated by Django 4.1.7 on 2023-03-01 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ustozlar', '0002_teacherdata_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='teacher_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
