# Generated by Django 4.1.7 on 2023-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustozlar', '0004_teacherdata_teacher_tel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherdata',
            options={'ordering': '', 'verbose_name': "Yangi ustoz qo'shish", 'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='teacher_img',
            field=models.ImageField(help_text="O'qituvchining rasmini qo'ying", upload_to='images/', verbose_name="O'qituvchi rasmi"),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='teacher_tel',
            field=models.CharField(help_text='Masalan: +998990327898', max_length=50, verbose_name="O'qituvchi telefon raqami: (qo'yish shart)"),
        ),
    ]
