# Generated by Django 4.1.7 on 2023-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Joy nomini kiriting: ')),
                ('img_location', models.ImageField(upload_to='images/', verbose_name='Joyning rasmini kiriting')),
                ('url_location', models.URLField(verbose_name='Silkani kiriting')),
            ],
            options={
                'verbose_name': "Maktabning 360° ko'rinishini qo'shish",
                'verbose_name_plural': "Maktab ko'rinishi 360 °",
            },
        ),
    ]
