# Generated by Django 4.1.7 on 2023-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name="To'liq ismi: ")),
                ('person', models.CharField(help_text='Masalan: 81-maktab direktori Oloviddin Ochilov', max_length=100, verbose_name="Ko'proq ma'lumot: ")),
                ('img_person', models.ImageField(upload_to='images/', verbose_name='Rasm: ')),
                ('web_url', models.URLField(help_text="Agar ushbu odamning veb sahifasi yo'q bo'lsa tashlab keting", verbose_name='Silkani kiriting')),
            ],
            options={
                'verbose_name': 'Maktab raxbariyati',
                'verbose_name_plural': 'Maktab raxbariyati',
            },
        ),
    ]
