# Generated by Django 4.1.7 on 2023-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewschool', '0002_schoolstaffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityPupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80, verbose_name="To'liq ismi: ")),
                ('text', models.TextField(help_text='Qanday yutuqga erishganki saytda turadigan shuni yozing!', verbose_name='Qanday yutuqga erishganligi: ')),
            ],
            options={
                'verbose_name': "Iqtidorli o'quvchilar",
                'verbose_name_plural': "Iqtidorli o'quvchilar",
            },
        ),
        migrations.AlterField(
            model_name='schoolstaffs',
            name='web_url',
            field=models.URLField(help_text="Agar ushbu odamning veb sahifasi yo'q bo'lsa buni kiriting: https://samshmaktab81.uz", verbose_name="Bog'lanish uchun silkani kiriting"),
        ),
    ]
