# Generated by Django 4.1.7 on 2023-04-03 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewschool', '0003_abilitypupils_alter_schoolstaffs_web_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitypupils',
            name='image_pupil',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name="O'quvchi rasmini kiriting"),
            preserve_default=False,
        ),
    ]
