# Generated by Django 4.1.7 on 2023-02-19 20:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Yangilik nomi')),
                ('date', models.DateField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField(verbose_name="Yangilik haqida to'liq ma'lumot")),
                ('image_news', models.ImageField(help_text='Iltimos yangilikga rasm yuklashni unutmang !', upload_to='images/', verbose_name='Yangilik rasmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ushbu maqolaning muallifi')),
            ],
            options={
                'verbose_name': "Yangilik qo'shish",
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
