# Generated by Django 4.1.7 on 2023-02-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tugatish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Yangi test qo'shish",
                'verbose_name_plural': 'Yangi test tuzish',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.IntegerField()),
                ('corrent_question', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlar.quizmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test natijalari',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-corrent_question'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_question', models.ImageField(blank=True, help_text="Agar klaviaturada yoza olmasangiz savolni rasmga olib faqat rasmini qo'ying", null=True, upload_to='images/', verbose_name="Agar savolingizni yozib bo'lmasa rasmini kiriting")),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlar.quizmodel')),
            ],
            options={
                'verbose_name': "Yangi savol qo'shish",
                'verbose_name_plural': "Savol qo'shish",
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlar.question')),
            ],
            options={
                'verbose_name': 'Test javoblari',
                'verbose_name_plural': 'Testlar javoblari',
            },
        ),
    ]
