# Generated by Django 4.1.7 on 2023-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Fan nomi'),
        ),
    ]
