# Generated by Django 4.1.7 on 2023-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlar', '0002_alter_quizmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(help_text="Agar savolingizni klaviaturada yozib bo'lmasa rasmini kiriting !", verbose_name='Savolni kiriting'),
        ),
    ]
