# Generated by Django 4.1.7 on 2023-03-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
