# Generated by Django 4.1.7 on 2023-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=60, verbose_name='slayd mavzusi: ')),
                ('slide_body', models.CharField(max_length=40, verbose_name='slayd tektstini kiriting: ')),
                ('slide_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
