# Generated by Django 4.1.7 on 2023-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_mainslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': "Slayder qo'shish", 'verbose_name_plural': "Slayder qo'shish"},
        ),
        migrations.AddField(
            model_name='mainslider',
            name='main_slide',
            field=models.BooleanField(default=False, help_text="agar tasqilasangiz veb saytga kirganda 1-bo'lib shu rasm ko'rinadi", verbose_name="Ushbu rasm veb saytga kirganda 1-bo'lib ko'rinsinmi?"),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='slide_img',
            field=models.ImageField(upload_to='images/', verbose_name="slaydga rasm qo'ying: "),
        ),
    ]
