# Generated by Django 4.1.7 on 2023-03-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_mainslider_options_mainslider_main_slide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='main_slide',
        ),
    ]
