# Generated by Django 4.1.7 on 2023-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_moreinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreinformation',
            options={'verbose_name': "Saytga ma'lumot qo'shish", 'verbose_name_plural': "Saytga ma'lumot qo'shish"},
        ),
    ]
