# Generated by Django 4.1.7 on 2023-03-11 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_alter_moreinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreinformation',
            options={'verbose_name': "Saytga ma'lumot qo'shish", 'verbose_name_plural': "Sayt ma'lumotlari"},
        ),
        migrations.AlterField(
            model_name='moreinformation',
            name='data_body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name="Ma'lumot haida to'liq xabar: "),
        ),
    ]
