# Generated by Django 4.1.7 on 2023-03-11 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_alter_moreinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinformation',
            name='data_body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000, message="Xato sizning kiritgan ma'lumotlaringiz 1000 ta belgidan oshib ketdi kamaytiring bo'lmasa bu xato sayt dizayniga ta'sir qiladi")], verbose_name="Ma'lumot haida to'liq xabar:"),
        ),
    ]
