# Generated by Django 4.1.7 on 2023-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_alter_moreinformation_data_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(max_length=50, verbose_name='Yangi menyu nomi: ')),
                ('url_menu', models.URLField(verbose_name='URL manzilni kiriting: ')),
            ],
            options={
                'verbose_name': "Saytga menyu qo'shish",
                'verbose_name_plural': "Saytga menyu qo'shish",
            },
        ),
    ]
