# Generated by Django 4.1.7 on 2023-03-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_addmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMenu',
        ),
    ]
