# Generated by Django 4.1.7 on 2023-04-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0012_delete_addmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldata',
            name='ishchi',
        ),
    ]
