# Generated by Django 4.1.7 on 2023-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_remove_schooldata_ishchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_tel', models.CharField(max_length=50, verbose_name='Maktab telefon raqami: ')),
                ('school_email', models.CharField(max_length=50, verbose_name='Maktab emaili: ')),
                ('school_tme', models.URLField(help_text="Bog'lanish uchun telegram manzil url ini kiriting", verbose_name='Telegram url: ')),
                ('school_youtube', models.URLField(help_text='YouTube url manzilini kiriting', verbose_name='YouTube url: ')),
                ('school_facebook', models.URLField(help_text='Facebook url manzilini kiriting', verbose_name='Facebook url: ')),
            ],
            options={
                'verbose_name': "Bog'lanish uchun",
                'verbose_name_plural': "Bog'lanish uchun",
            },
        ),
    ]
