# Generated by Django 4.1.7 on 2023-04-02 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0014_schoolcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcontact',
            name='school_instagram',
            field=models.URLField(default=django.utils.timezone.now, help_text='Instagram url manzilini kiriting', verbose_name='Instagram url: '),
            preserve_default=False,
        ),
    ]
