# Generated by Django 4.1.7 on 2023-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0015_schoolcontact_school_instagram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSlider',
        ),
    ]
