# Generated by Django 4.1.7 on 2024-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0017_contact_faq_delete_topworkers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': "Ko'p berilgan savol", 'verbose_name_plural': "Ko'p berilgan savollar"},
        ),
        migrations.AlterField(
            model_name='moreinformation',
            name='data_title',
            field=models.CharField(max_length=256, verbose_name="Ma'lumot mavzusi: "),
        ),
    ]
